### ISSUE TITLE
Adding new character

### ISSUE THREAD

**Issue by ArksisSH** [ukon1990/wow-auction-helper#91] opened 2020-06-12 15:12 UTC
Hi there

first of all, incredible work! Thank you for this amazing tool!

I recently restarted my PC and forgot to export the settings. When I set up the characters again, I could not load them anymore (except under lvl 10). Is this problem known?

Best regards

**Comment by ukon1990** [comment] 2020-06-15 06:29
Hi and thanks!

Hmm, it should work. You have been logged onto those characters recently I assume.

I am currently working on updating the known recipe part of characters. This part of the app have not been available for "new" characters since Blizzard added their API. It became available a couple weeks ago. But I haven't had the time to fix it until now.

Anyways, Il'l set a reminder to look into this after work today! Thanks for reporting!

**Comment by ukon1990** [comment] 2020-06-15 19:12
@ArksisSH Hmm, I could not replicate it in inkognito mode. Does your character contain special characters or something that might cause issues?

The one I tried with does contain "Ø", and that seemed to work just fine.

**Comment by ArksisSH** [comment] 2020-06-17 07:28
@ukon1990 
Sorry for the late reply. No, the name does not contain any special characters.
I tried it on different computers and different networks.

Only the character adding function is not working - everything else does it's job. So the auctions/items are loading properly and as intended.

**Comment by ArksisSH** [comment] 2020-06-17 07:34
Ah, and the TSM Data is also not loading - do you have a logging function? so I can send you my logs?
If you need any details, I'll provide it to you asap.

**Comment by ukon1990** [comment] 2020-06-17 13:14
@ArksisSH I can see that some characters have failed but I don't know which so I haven't been able to reproduce it. Do you feel comfortable sending me the realm, character name and region? (you could do it via PM if possible, if you don't want to post it on the issue)

Regarding TSM, then it seems like some realms have not had their TSM data updated in too long(due to incorrect sorting in SQL) so it was deleted by a rule I had set in AWS S3 🤣 It should be fixed now, but it might take some time until all the realms have current TSM data again. Thanks for reporting that also!

**Comment by ArksisSH** [comment] 2020-06-19 06:04
Of course:

Realm: Gilneas (eu)

Character: Arksa

 

Von: Jonas <notifications@github.com> 
Gesendet: Mittwoch, 17. Juni 2020 15:15
An: ukon1990/wow-auction-helper <wow-auction-helper@noreply.github.com>
Cc: ArksisSH <kneazle@gmx.net>; Mention <mention@noreply.github.com>
Betreff: Re: [ukon1990/wow-auction-helper] Adding new character (#91)

 

@ArksisSH <https://github.com/ArksisSH>  I can see that some characters have failed but I don't know which so I haven't been able to reproduce it. Do you feel comfortable sending me the realm, character name and region? (you could do it via PM if possible, if you don't want to post it on the issue)

Regarding TSM, then it seems like some realms have not had their TSM data updated in too long(due to incorrect sorting in SQL) so it was deleted by a rule I had set in AWS S3 🤣 It should be fixed now, but it might take some time until all the realms have current TSM data again. Thanks for reporting that also!

**Comment by ukon1990** [comment] 2020-06-20 07:40
@ArksisSH Thanks! And solved!
So the problem was as simple as your character not being in a guild.
Even if obvious, I did not take that to consideration, that some characters are guildless when I updated to the new Blizzard API 😂

Thanks for the report!

**Closed by ukon1990** 2020-06-20 07:40 UTC
Labels: bug, cannot reproduce
