### ISSUE TITLE
Incorrect Vendor Sell Price

### ISSUE THREAD

**Issue by ghost** [ukon1990/wow-auction-helper#88] opened 2020-02-23 21:30 UTC
![image](https://user-images.githubusercontent.com/25420288/75120366-2df5a800-5683-11ea-8730-b50724a0c35c.png)

Shows the following items: -
```
Lava Bolt Crossbow (Vendor Sell Price: 123g 78s 50c)
Chelley's Sterilized Scalpel (Vendor Sell Price: 104g 87s 97c)
Soul Blade (Vendor Sell Price: 99g 26s 61c)
Rowan's Rifle of Silver Bullets (Vendor Sell Price: 116g 28s 18c)
Ranseur of Hatred (Vendor Sell Price: 124g 62s 0c)
```
Actual vendor prices: -
```
Lava Bolt Crossbow (Vendor Sell Price: 34g 22s 20c)
Chelley's Sterilized Scalpel (Vendor Sell Price: 27g 56s 22c)
Soul Blade (Vendor Sell Price: 27g 94s 53c)
Rowan's Rifle of Silver Bullets (Vendor Sell Price: 26g 51s 40c)
Ranseur of Hatred (Vendor Sell Price: 34g 45s 28c)
```

**Comment by ukon1990** [comment] 2020-02-24 07:29
Thank you for the feedback. Going to see if I can fix this later today.

The prices are directly from blizzards API, but for some reason they returned the wrong prices. It seems like it only affects weapons for some reason. unless I am mistaken.

I see that the "community API" of theirs still returns 123g as the price. However, it seems like this is solved with their new "game data API". I see that wowed also has the incorrect price for this item (and other weapons).

**Comment by ukon1990** [comment] 2020-02-25 13:16
This issue should now be resolved.

All of the armor and weapons in Wotlk - WoD has now been updated from blizzards new API data.
If it is not appearing correctly for you, you might need to re-download the item data. But it should not be needed, it should be updated automatically.

The vendor price will now also be shown as of version 3.15.2.

**Comment by ukon1990** [comment] 2020-02-25 21:53
Nope. Still seem like some items get the incorrect value from Blizzard, but most are fixed. I haven't gotten a response from Blizzard's API devs yet, might be something I'm missing…

**Comment by thgilartlU** [comment] 2020-03-01 19:04
The Item API GET /data/wow/item/71366 (Lava Bolt Crossbow) returns the following: -

    ],
    "sell_price": {
      "value": 342220,
      "display_strings": {
        "header": "Sell Price:",
        **"gold": "34",
        "silver": "22",
        "copper": "20"**
      }

However, I'm not sure you can use this same call for items that have scaling applied.

**Comment by ukon1990** [comment] 2020-03-03 06:01
That Item should already be fixed, but it should only be those who scale left I think.
And I think you're correct regarding the scaling, but as far as I can remember, the AH API does not provide the "gotten at level" data (yet). But I might need to doublecheck that.
But if it is correct, that there is no information about that, then it might be better to hide those items from the "vendor sell" dashboard. Until they provide this information that is.

**Comment by ukon1990** [comment] 2020-09-15 20:06
Closing this issue.
The issue is mainly with equipment. By default gear is not included in the vendor sell price board.
I can't remember finding any good solution to this problem, as Blizzard does not provide this information. At least not in a way that I am aware of.

If anyone finds a good solution to this, feel free to let me know.

**Closed by ukon1990** 2020-09-15 20:06 UTC
Labels: medium priority

**Comment by develflowing** [comment] 2021-06-18 20:37
Hello. 
Any solution? wowhead I think have a scale of item level and sale to vendor price. I checked on one item - it's 11.03% price change beetween item levels. I didn't understand how to use ITEM CURVES from https://www.raidbots.com/developers
Any help?
Thanks.
